### ISSUE TITLE
The problem of `store_hook` around neo-tree.nvim still persists

### ISSUE THREAD

**Issue by nyngwang** [GnikDroy/projections.nvim#10] opened 2022-12-10 05:58 UTC
That is: If I restore a project that has a neo-tree window open before saving it, I will have a chance to see the following result:

1. There is a split with no content, and its `filetype`(as the `set ft?` shown) is `neo-tree`.
2. If I don't close that empty window, the same problem will happen again on the next resume. (This would mean that those `store_hooks` are not working!)

<img src="https://user-images.githubusercontent.com/24765272/206831569-5af451d1-39f4-4677-8bdd-72647ca85240.png" width="700">

With point 1., the toggle to open/close neo-tree will cause an error. And this is quite annoying since I will have to manually close all the neo-tree splits(as I usually use many tabs) and then reopen the project(to solve point 2.):

```
Error executing vim.schedule lua callback: .../packer/start/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:1009: attempt to index field 'tree' (a nil value)
stack traceback:
        .../packer/start/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:1009: in function 'draw'
        .../packer/start/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:1142: in function 'show_nodes'
        ...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:95: in function 'render_context'
        ...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:118: in function <...ree.nvim/lua/neo-tree/sources/filesystem/lib/fs_scan.lua:117>
```

## Config

neo-tree

```
require('neo-tree').setup()
```

projections.nvim

```lua
require('projections').setup {
  workspaces = require('project.projects'),
  patterns = {
    'init.lua',
    '.git',
  },
  store_hooks = {
    pre = function ()
      vim.cmd('tabd Neotree close')
      vim.cmd('tabn')
    end,
    post = function () end,
  },
  restore_hooks = {
    pre = function () end,
    post = function () end,
  },
}
```

**Comment by GnikDroy** [comment] 2022-12-10 08:00
I somehow cannot reproduce this. Everything works fine on my machine. Could you attach the `neo-tree` config as well?

Additionally, can you explain what you mean by, `If I restore a project that has a neo-tree window open before saving it`

Could you also perhaps a share a screencast? Or detailed steps to reproduce this.

**Comment by nyngwang** [comment] 2022-12-10 08:11
> Additionally, can you explain what you mean by, If I restore a project that has a neo-tree window open before saving it.

Apologies for my bad English. I meant: I will not manually close all existing neo-tree windows before I run `:wq`, which triggers the `VimLeave` event that saves the session.

> Could you attach the neo-tree config as well?

I'm kinda reluctant to copy-paste it directly because I made this config really big(around 300 lines) and I think most of them are not indeed related to the problem. I will try to exclude all those UI decorations and leave those important parts so I will be more readable. I will tag you when I finish the filtering.

**Comment by nyngwang** [comment] 2022-12-10 08:38
@GnikDroy: I think I just figured out how to 100% reproduce the problem:

1. Add the following part into neo-tree's setup table:

```lua
require('neo-tree').setup {
  use_default_mappings = false,
  close_if_last_window = true,
    filesystem = {
      hijack_netrw_behavior = 'open_default',
      follow_current_file = true,
      use_libuv_file_watcher = true, -- no need to refresh the filetree
      async_directory_scan = 'always',
      bind_to_cwd = true, -- sync neo-tree and vim's cwd.
        window = {
          mappings = {
            ['-'] = 'navigate_up',
            ['<C-]>'] = 'set_root',
          }
        }
      }
    }
  }
}
```

2. Open an existing project with projections.nvim.
3. Toggle neo-tree open, then use `<C-]>` to trigger `set_root`(i.e. I think this is indeed `cwd` internally) to change the current working directory to any subfolder of the current project.
4. Exit NeoVim with `:wqa`.
5. Reopen NeoVim and switch back to the project and step 2.

OK

**Comment by GnikDroy** [comment] 2022-12-10 08:56
@nyngwang I understand now.

The recommended config has changed. 😳

```lua
        -- Autostore session on VimExit
        local Session = require("projections.session")
        vim.api.nvim_create_autocmd({ 'VimLeavePre' }, {
            callback = function() Session.store(vim.loop.cwd()) end,
        })
```

I no longer recommend to store sessions on changed directory event. Due to problems like this:

I came to this conclusion due to two reasons:

1) Firstly I shouldn't change behaviour of `:cd`. It should work like `cd`.

2) If user wants to switch session with `:cd` as well they can create a new `:Cd` command, where they use switcher.

**Comment by nyngwang** [comment] 2022-12-10 09:06
@GnikDroy Many thanks for your instant reply(ies). Sorry about my messy comments above (still my life lesson to learn how to simplify things into simple words) I did guess the problem is probably:

1. A issue on the neo-tree side.
2. A problem that should not be called a bug, but just my misconfiguration on those `autocmd`s.

Anyway, let me try to understand your suggestion and update this comment during my reading.

**Comment by GnikDroy** [comment] 2022-12-10 09:33
Projections still changes the directory when switching projects. `:FzfLua live_grep_glob` `:FzfLua files` should still work I think.

It's only not *recommended* to **store** session on the `DirChangedPre`. This is only a recommendation, after all projections doesn't really try to force a workflow. If you are ONLY using projections, this recommendation makes sense, since `switcher()` takes care of storing your session when you switch projects. An additional `autocmd` with `DirChangedPre` doesn't provide much value. 

Yes, Removing the `autocmd` for `DirChangedPre` will not load the session when you `:cd` into said project's directory. But if you wanted to do this, you could've just used `projections` :). This is what it's for. Also, it allows you to temporarily `:cd` into a directory without loading the session.

But it is perfectly valid to want this behaviour with `DirChangedPre`. You are free to do what you want, and if `projections` causes issues, I will try to fix them.

I tested your steps with my current config, and couldn't reproduce the issue. So, I thought maybe it was due to the recommended config. I will try enabling the `DirChangedPre` autocmd and try again.

**Comment by nyngwang** [comment] 2022-12-10 09:44
@GnikDroy How to keep the `cwd` fixed for each project even if I once ran `:cd`/`switcher()` during the recording of the session? In my current workflow I will first use  fzf-lua-projections.nvim to list all existing projects. Say I have one called:

```
/path/to/my/dotfiles
```

I will expect my `cwd` set to `/path/to/my/dotfiles` even if I changed the `cwd` to some subfolder when I was editing the project previously. Is this possible? And the inconsistency of `cwd` seems to be the cause of my bug demo [above](https://github.com/GnikDroy/projections.nvim/issues/10#issuecomment-1345181092). As you can see one of the error says:

```
/Users/ningwang/GitHub/dotfiles/.config/nvim/.config/nvim
                                             ^~~~~~~~~~~^
```

but the trailing `.config/nvim` is redundant. If the `cwd` could always be `/Users/ningwang/GitHub/dotfiles/` then I think my problem is solved and this issue can be closed.

**Comment by GnikDroy** [comment] 2022-12-10 10:00
@nyngwang I cannot reproduce [this](https://github.com/GnikDroy/projections.nvim/issues/10#issuecomment-1345186263) with the telescope.

I will try with fzf and your plugin

**Comment by GnikDroy** [comment] 2022-12-10 10:31
@nyngwang 

I cannot seem to reproduce this with your plugin + fzf either 😂 . I think I am following the correct steps.

https://user-images.githubusercontent.com/30725674/206850538-2cb5da85-246f-4e11-9a4e-8d643cd92a8e.mp4

**Comment by GnikDroy** [comment] 2022-12-10 10:36
Here is my full config with projections + fzf-lua + fzf-lua-projections.vim

```lua
return function(use)
    use({
        'gnikdroy/projections.nvim',
        requires = {
            'ibhagwan/fzf-lua',
            'nyngwang/fzf-lua-projections.nvim',
        },
        config = function()
            require("projections").setup({
                workspaces = { { '~/Documents/dev', { ".git" } } },
                store_hooks = {
                    pre = function()
                        -- neo-tree
                        if pcall(require, "neo-tree") then
                            vim.cmd("tabd Neotree close")
                            vim.cmd("tabn")
                        end
                    end,
                },
            })

            -- Store session automatically on exit
            local Session = require("projections.session")
            vim.api.nvim_create_autocmd({ 'VimLeavePre', 'DirChangedPre' }, {
                callback = function() Session.store(vim.loop.cwd()) end,
                desc = "Store project session",
            })

            -- Switch to project if vim was started in a project dir
            local switcher = require("projections.switcher")
            vim.api.nvim_create_autocmd({ "VimEnter" }, {
                callback = function()
                    if vim.fn.argc() == 0 then switcher.switch(vim.loop.cwd()) end
                end,
                desc = "Restore project session if nvim started in a project dir",
            })

            -- change with fzf_lua
            -- local NOREF_NOERR_TRUNC = { noremap = true, silent = true, nowait = true }
            vim.keymap.set('n', '<Leader>cp', function() require('fzf-lua-p').projects() end,
                { silent = true, nowait = true })
        end
    })
end
```

**Comment by nyngwang** [comment] 2022-12-10 10:43
@GnikDroy I'm at `branch = "main"` and have this extra `autocmd`, which is added to cope with the `<C-]>` of neo-tree:

I will try to reproduce it again with your config.

```lua
-- auto-restore on neo-tree change root.
vim.api.nvim_create_autocmd({ 'DirChanged' }, {
  group = 'session.lua',
  pattern = '*',
  callback = function ()
    require('projections.switcher').switch(vim.loop.cwd())
  end
})
```

**Comment by GnikDroy** [comment] 2022-12-10 10:50
Can you also check if my config produces the error on your machine?

**Comment by nyngwang** [comment] 2022-12-10 10:58
@GnikDroy Lol, it turns out that this bug is not related to `fzf-lua`,`neo-tree`,`projections.nvim`. I removed the [glepnir/dashboard-nvim](https://github.com/glepnir/dashboard-nvim), which I fixed my commit to `a36b32`, and the problem disappear!

**Comment by GnikDroy** [comment] 2022-12-10 11:01
Yes, can confirm that dashboard-nvim causes this. Weird.

**Comment by nyngwang** [comment] 2022-12-10 11:04
Really thank you for enduring my messy comments! I HATE CROSS-PLUGIN CONFLICTS!

**Comment by GnikDroy** [comment] 2022-12-10 11:07
No problem. I will investigate what exactly causes this conflict later. Always have to be careful if the problem is from my end.

Also, I used your plugin for some time, and it feels very natural.

If you want to, we can officially add your fzf plugin into the main repository as well. I don't use fzf, so you can maintain it directly from here.

**Comment by nyngwang** [comment] 2022-12-10 11:13
> If you want to, we can officially add your fzf plugin into the main repository as well. I don't use fzf, so you can maintain it directly from here. Completely optional, of course.

Feel free to copy-paste it into your repo :) (or wait me a second to create a PR) I thought my idea is hard to implement but it turned out that the code is pretty short, so indeed no need to create a separate repo.

**Comment by GnikDroy** [comment] 2022-12-10 11:16
No pressure. I will wait for your PR if you have time. As other users haven't requested this yet, I have no strong feelings. The decision is yours, just letting you know that it is welcome here. 😄

**Comment by GnikDroy** [comment] 2022-12-10 11:32
So dashboard-nvim also seems to have support for sessions which is apparently not opt-out according to this:

https://github.com/glepnir/dashboard-nvim/issues/217

So, this causes conflict with projections.nvim. Therefore, I am closing this issue.

**Closed by GnikDroy** 2022-12-10 11:32 UTC
